INSERT INTO ingredient VALUES (1, "Unsalted Crackers", 140, "cracker", 1.23);
INSERT INTO ingredient VALUES (2, "Unsalted Butter", 15, "oz", 2.94);
INSERT INTO ingredient VALUES (3, "Brown Sugar", 32, "oz", 2.73);
INSERT INTO ingredient VALUES (4, "Sea Salt", 4.4, "oz", 0.98);
INSERT INTO ingredient VALUES (5, "Vanilla Extract", 2, "floz", 4.98);
INSERT INTO ingredient VALUES (6, "Semi-Sweet Chocolate Chips", 11, "oz", 1.74);
INSERT INTO ingredient VALUES (7, "Milk", 64, "floz", 1.31);
INSERT INTO ingredient VALUES (8, "Yeast", 2.25, "tsp", 0.80);
INSERT INTO ingredient VALUES (9, "White Sugar", 64, "oz", 2.00);
INSERT INTO ingredient VALUES (10, "Eggs", 11, "egg", 0.89);
INSERT INTO ingredient VALUES (11, "Cinnamon", 2.5, "oz", 1.18);
INSERT INTO ingredient VALUES (12, "Nutmeg", 1.8, "oz", 5.94);
INSERT INTO ingredient VALUES (13, "Allspice", 1.6, "oz", 3.97);
INSERT INTO ingredient VALUES (14, "Bread Flour", 80, "oz", 3.32);
INSERT INTO ingredient VALUES (15, "Dried Cherries", 5, "oz", 2.58);

INSERT INTO recipe VALUES (1, "Chocolate Caramel Toffee", 24, NULL, 20.0);
INSERT INTO recipe VALUES (2, "Hot Cross Buns", 14, "Rolls", 30.0);

INSERT INTO recipe_ingredient VALUES (1, 1, 40, "cracker");
INSERT INTO recipe_ingredient VALUES (1, 2, 8, "oz");
INSERT INTO recipe_ingredient VALUES (1, 3, 8, "oz");
INSERT INTO recipe_ingredient VALUES (1, 4, 0.25, "tsp");
INSERT INTO recipe_ingredient VALUES (1, 5, 0.5, "tsp");
INSERT INTO recipe_ingredient VALUES (1, 6, 11, "oz");
INSERT INTO recipe_ingredient VALUES (2, 7, 6, "floz");
INSERT INTO recipe_ingredient VALUES (2, 8, 2.25, "tsp");
INSERT INTO recipe_ingredient VALUES (2, 9, 1, "tsp");
INSERT INTO recipe_ingredient VALUES (2, 3, 4, "oz");
INSERT INTO recipe_ingredient VALUES (2, 2, 2.5, "oz");
INSERT INTO recipe_ingredient VALUES (2, 5, 0.5, "tsp");
INSERT INTO recipe_ingredient VALUES (2, 10, 2, "egg");
INSERT INTO recipe_ingredient VALUES (2, 4, 1, "tsp");
INSERT INTO recipe_ingredient VALUES (2, 11, 1.25, "tsp");
INSERT INTO recipe_ingredient VALUES (2, 12, 0.5, "tsp");
INSERT INTO recipe_ingredient VALUES (2, 13, 0.5, "tsp");
INSERT INTO recipe_ingredient VALUES (2, 14, 17.9, "oz");
INSERT INTO recipe_ingredient VALUES (2, 15, 5, "oz");